import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_crashlytics/firebase_crashlytics.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:google_mobile_ads/google_mobile_ads.dart';
import 'package:provider/provider.dart';

import 'firebase_options.dart';
import 'l10n/l10n.dart';
import 'persistence/save_system.dart';
import 'platform/ad_reward_service.dart';
import 'platform/consent_manager.dart';
import 'platform/flutter_platform_service.dart';
import 'platform/game_services_service.dart';
import 'platform/google_sign_in_service.dart';
import 'platform/interstitial_ad_service.dart';
import 'platform/purchase_service.dart';
import 'state/account_state.dart';
import 'state/friends_service.dart';
import 'state/game_state.dart';
import 'state/promo_code_service.dart';
import 'theme/theme.dart' as dk_theme;
import 'ui/root/root_view.dart';

/// `SaveSystem.load()` (and therefore `GameState.create`) is genuinely
/// async — see `lib/persistence/save_system.dart` — so app start has to
/// await it before `runApp`, unlike Swift's synchronous `GameState()`
/// (`RootView.init`). `WidgetsFlutterBinding.ensureInitialized()` is
/// required before any async work runs ahead of `runApp`.
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // Backs `CloudSaveStore` (save sync), the friend-code lookup
  // (`FriendsService`), and the cross-platform Arena leaderboard — see
  // `lib/firebase_options.dart`
  // (generated by `flutterfire configure` against the `dreamkeepers-292f4`
  // Firebase project) and each feature's own doc comment for how it uses
  // this. Must run before anything below that could touch Firebase.
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  // Route uncaught Flutter framework errors to Crashlytics instead of just
  // the debug console — mirrors the Swift build's crash reporting. Kept
  // off in debug builds so local stack traces still print to the terminal
  // the way they always have.
  if (!kDebugMode) {
    FlutterError.onError = FirebaseCrashlytics.instance.recordFlutterFatalError;
    PlatformDispatcher.instance.onError = (error, stack) {
      FirebaseCrashlytics.instance.recordError(error, stack, fatal: true);
      return true;
    };
  }
  // Landscape-only, matching the iOS original (Resources/Info.plist ships
  // just LandscapeLeft/LandscapeRight). Every screen is laid out against a
  // wide, short reference size; portrait overflows.
  await SystemChrome.setPreferredOrientations(const [
    DeviceOrientation.landscapeLeft,
    DeviceOrientation.landscapeRight,
  ]);
  // Real AdMob/Play Billing services, not the Mock* ones — see
  // `AdMobRewardService`/`AdMobInterstitialAdService`/
  // `GooglePlayPurchaseService`'s doc comments for the test-ad-unit and
  // Play-Console-product caveats until real Android IDs replace them.
  await MobileAds.instance.initialize();
  // Resolve the active language and prime the global `L` *before* building
  // `GameState` — `GameState.create` touches the localized catalogs
  // (`DreamkeeperCatalog.starter` and friends), which read `L` on first
  // access. The Settings language switch forces a full restart, so the
  // locale never changes mid-session and `MaterialApp` can take a fixed
  // `locale`. `L` gives non-widget code (notifications, reward toasts,
  // catalogs) the same strings.
  final locale = resolvePreferredLocale(await LocalSaveStore.readPreferredLanguage());
  await loadGlobalLocalizations(locale);
  final gameState = await GameState.create(
    platform: FlutterPlatformService(),
    adService: AdMobRewardService(),
    interstitialAdService: AdMobInterstitialAdService(),
    purchaseService: GooglePlayPurchaseService(),
  );
  final accountState = AccountState();
  await accountState.load();
  runApp(DreamkeepersApp(gameState: gameState, accountState: accountState, locale: locale));
}

class DreamkeepersApp extends StatelessWidget {
  final GameState gameState;
  final AccountState accountState;
  final Locale locale;
  const DreamkeepersApp({
    super.key,
    required this.gameState,
    required this.accountState,
    this.locale = const Locale('en'),
  });

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider<GameState>.value(value: gameState),
        ChangeNotifierProvider<AccountState>.value(value: accountState),
        // Android counterparts to Game Center / Sign in with Apple — see
        // `platform/game_services_service.dart` and
        // `platform/google_sign_in_service.dart`. Constructed here (not in
        // `create()`-style factories like GameState) since neither needs
        // async setup before the widget tree exists.
        ChangeNotifierProvider<GameServicesService>(create: (_) => GameServicesService()),
        ChangeNotifierProvider<GameLeaderboardService>(create: (_) => GameLeaderboardService()),
        Provider<GoogleSignInService>(create: (_) => GoogleSignInService()),
        // 8-digit-code friends (State/FriendsService.swift's counterpart) —
        // see `lib/state/friends_service.dart`'s doc comment.
        ChangeNotifierProvider<FriendsService>(create: (_) => FriendsService()),
        // Developer-configured gift codes — see
        // `lib/state/promo_code_service.dart`'s doc comment.
        ChangeNotifierProvider<PromoCodeService>(create: (_) => PromoCodeService()),
      ],
      child: MaterialApp(
        title: 'Dreamkeepers',
        debugShowCheckedModeBanner: false,
        locale: locale,
        supportedLocales: AppLocalizations.supportedLocales,
        localizationsDelegates: const [
          AppLocalizations.delegate,
          GlobalMaterialLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
          GlobalCupertinoLocalizations.delegate,
        ],
        theme: ThemeData(
          brightness: Brightness.dark,
          scaffoldBackgroundColor: dk_theme.Theme.deepNavy,
          useMaterial3: true,
        ),
        // Real UMP consent flow — see `platform/consent_manager.dart`'s
        // doc comment for why this is passed explicitly instead of
        // relying on RootView's NoopConsentService default.
        home: RootView(consentService: UmpConsentService()),
      ),
    );
  }
}
